dashboard/models.py
from sqlalchemy.dialects.postgresql import JSONB

from app import db


class OAManual(db.Model):
    __bind_key__ = "unpaywall_db"
    __tablename__ = "oa_manual"

    id = db.Column(db.Integer, primary_key=True)
    doi = db.Column(db.Text, unique=True)
    response_jsonb = db.Column(JSONB)


class JournalOAYearOverride(db.Model):
    __bind_key__ = "unpaywall_db"
    __tablename__ = "journal_oa_year_override"

    issn_l = db.Column(db.Text, primary_key=True)
    oa_year = db.Column(db.Integer)


class ConvertedToHttps(db.Model):
    """Model for to convert all URLs from a domain from http to https."""

    __bind_key__ = "unpaywall_db"
    __tablename__ = "convert_http_to_https"

    id = db.Column(db.Integer, primary_key=True)
    hostname = db.Column(db.Text, unique=True)

dashboard/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired


class DOIForm(FlaskForm):
    doi = StringField(
        "DOI", validators=[DataRequired()], render_kw={"placeholder": "10.1234/1234"}
    )
    submit = SubmitField("Submit")

app.py
import os

from flask import Flask
import sentry_sdk
from sentry_sdk.integrations.flask import FlaskIntegration

from extensions import db, login_manager, rq
import auth
import dashboard

app = Flask(__name__)

sentry_sdk.init(
    dsn=os.environ.get("SENTRY_DSN"),
    integrations=[
        FlaskIntegration(),
    ],
)

uri = os.environ.get("DATABASE_URL")
if uri.startswith("postgres://"):
    uri = uri.replace("postgres://", "postgresql://", 1)

app.config["SECRET_KEY"] = os.getenv("SECRET_KEY", "dev")
app.config["SQLALCHEMY_DATABASE_URI"] = uri
app.config["SQLALCHEMY_BINDS"] = {"unpaywall_db": os.environ.get("UNPAYWALL_DB")}
app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False
app.config["RQ_REDIS_URL"] = os.environ.get("REDIS_URL", "redis://localhost:6379")

app.register_blueprint(auth.views.auth_blueprint)
app.register_blueprint(dashboard.views.dashboard_blueprint)

db.init_app(app)
login_manager.init_app(app)
rq.init_app(app)


if __name__ == "__main__":
    app.run()

dashboard/__init__.py
from . import views

dashboard/views.py
import time
import re
from urllib.parse import urlparse

from flask import (
    Blueprint,
    render_template,
    redirect,
    url_for,
    Markup,
    request,
    jsonify,
)
from flask_login import login_required, current_user
import requests
from rq.queue import Queue
from rq.job import Job
from rq.registry import StartedJobRegistry, FinishedJobRegistry, FailedJobRegistry

from app import db, rq
from dashboard.background import refresh_doi_background
from dashboard.forms import DOIForm
from dashboard.models import OAManual, JournalOAYearOverride, ConvertedToHttps
from dashboard.utils import is_doi_manually_closed, insecure_url


dashboard_blueprint = Blueprint("dashboard", __name__)


@dashboard_blueprint.route("/")
@login_required
def dashboard():
    form = DOIForm()
    doi = request.args.get("doi")
    not_in_unpaywall = False
    http_url = None
    result = None
    other_oa_locations = []
    manually_closed = is_doi_manually_closed(doi)
    if doi:
        r = requests.get(
            f"https://api.unpaywall.org/v2/{doi}?email=support@unpaywall.org"
        )
        if "HTTP_status_code" in r.json() and r.json()["HTTP_status_code"] == 404:
            result = None
            not_in_unpaywall = True
        else:
            result = dict(r.json())

        if result and result.get("oa_locations"):
            other_oa_locations = result.get("oa_locations")[1:]
        else:
            other_oa_locations = []

        if result:
            http_url = insecure_url(result)

    return render_template(
        "index.html",
        current_user=current_user,
        form=form,
        result=result,
        doi=doi,
        http_url=http_url,
        manually_closed=manually_closed,
        not_in_unpaywall=not_in_unpaywall,
        other_oa_locations=other_oa_locations,
    )


@dashboard_blueprint.route("/refresh-doi", methods=["GET", "POST"])
@login_required
def refresh_doi():
    form = DOIForm()
    if form.validate_on_submit():
        refresh_doi_background.queue(
            form.doi.data, description=form.doi.data, result_ttl=24 * 60 * 60
        )
        time.sleep(0.3)
        return redirect(url_for("dashboard.refresh_doi"))
    queue = Queue("default", connection=rq.connection)
    started_jobs = StartedJobRegistry("default", connection=rq.connection)
    finished_jobs = FinishedJobRegistry("default", connection=rq.connection)
    failed_jobs = FailedJobRegistry("default", connection=rq.connection)
    job_ids = (
        started_jobs.get_job_ids()
        + queue.get_job_ids()
        + finished_jobs.get_job_ids()
        + failed_jobs.get_job_ids()
    )
    results = []
    for job_id in job_ids:
        job = Job.fetch(job_id, connection=rq.connection)
        if job.result:
            try:
                result = re.sub("\d+:", "<br>", job.result)
                result = result.replace("<meta http-equiv=", "")
                result = Markup(result)
            except TypeError:
                result = job.result
        else:
            result = None
        results.append(
            {
                "doi": job.description,
                "status": job.get_status(),
                "result": result,
                "timestamp": job.enqueued_at,
            }
        )
        results = sorted(results, key=lambda d: d["timestamp"], reverse=True)
    return render_template(
        "refresh_doi.html", current_user=current_user, form=form, results=results
    )


@dashboard_blueprint.route("/refresh-doi/<path:doi>")
@login_required
def start_refresh(doi):
    job = refresh_doi_background.queue(
        doi, description=doi, result_ttl=24 * 60 * 60, timeout=60 * 10
    )
    return jsonify({"job_id": job.get_id()})


@dashboard_blueprint.route("/refresh-status/<path:job_id>")
@login_required
def refresh_status(job_id):
    job = Job.fetch(job_id, connection=rq.connection)
    if job.result and job.is_finished:
        result = job.result
    else:
        result = None
    return jsonify(
        {
            "status": job.get_status(),
            "result": result,
            "timestamp": job.enqueued_at,
        }
    )


@dashboard_blueprint.route("/add-manual")
@login_required
def add_manual():
    doi = request.args.get("doi")
    if doi:
        doi = doi.strip().replace("https://doi.org/", "")
        if not OAManual.query.filter_by(doi=doi).first():
            oa_manual = OAManual(doi=doi)
            db.session.add(oa_manual)
            db.session.commit()
    return redirect(url_for("dashboard.dashboard", doi=doi))


@dashboard_blueprint.route("/open-doi")
@login_required
def open_doi():
    doi = request.args.get("doi")
    if doi:
        doi = doi.strip().replace("https://doi.org/", "")
        oa_manual = OAManual.query.filter_by(doi=doi).first()
        db.session.delete(oa_manual)
        db.session.commit()
    return redirect(url_for("dashboard.dashboard", doi=doi))


@dashboard_blueprint.route("/guide")
@login_required
def guide():
    return render_template("guide.html", current_user=current_user)


@dashboard_blueprint.route("/journal-oa-year-override")
@login_required
def journal_oa_year_override():
    issn_l = request.args.get("issn_l")
    year = request.args.get("year")
    if issn_l and year:
        # check if it already exists
        journal_oa_year_override = JournalOAYearOverride.query.filter_by(
            issn_l=issn_l
        ).first()
        if journal_oa_year_override:
            return redirect(url_for("dashboard.dashboard"))
        else:
            journal_oa_year = JournalOAYearOverride(issn_l=issn_l, oa_year=int(year))
            db.session.add(journal_oa_year)
            db.session.commit()
            return redirect(url_for("dashboard.dashboard"))


@dashboard_blueprint.route("/convert-domain-to-https")
@login_required
def convert_domain_to_https():
    url = request.args.get("url")
    doi = request.args.get("doi")
    hostname = urlparse(url).hostname
    if hostname:
        c = ConvertedToHttps(hostname=hostname)
        db.session.add(c)
        db.session.commit()
    return redirect(url_for("dashboard.dashboard", doi=doi))

templates/_header.html
<!DOCTYPE html>
<html lang="en-US" dir="ltr">

  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <!-- ===============================================-->
    <!--    Document Title-->
    <!-- ===============================================-->
    <title>Unpaywall Dashboard</title>


    <!-- ===============================================-->
    <!--    Favicons-->
    <!-- ===============================================-->
    <link rel="apple-touch-icon" sizes="180x180" href="/static/assets/img/favicon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/static/assets/img/favicon.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/static/assets/img/favicon.png">
    <link rel="shortcut icon" type="image/x-icon" href="/static/assets/img/favicon.png">
    <link rel="manifest" href="/static/assets/img/favicons/manifest.json">
    <meta name="msapplication-TileImage" content="/static/assets/img/favicons/mstile-150x150.png">
    <meta name="theme-color" content="#ffffff">
    <script src="/static/assets/js/config.js"></script>
    <script src="/static/vendors/simplebar/simplebar.min.js"></script>


    <!-- ===============================================-->
    <!--    Stylesheets-->
    <!-- ===============================================-->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,500,600,700%7cPoppins:300,400,500,600,700,800,900&amp;display=swap" rel="stylesheet">
    <link href="/static/vendors/simplebar/simplebar.min.css" rel="stylesheet">
    <link href="/static/assets/css/theme-rtl.min.css" rel="stylesheet" id="style-rtl">
    <link href="/static/assets/css/theme.min.css" rel="stylesheet" id="style-default">
    <link href="/static/assets/css/user-rtl.min.css" rel="stylesheet" id="user-style-rtl">
    <link href="/static/assets/css/user.min.css" rel="stylesheet" id="user-style-default">
    <script>
      var isRTL = JSON.parse(localStorage.getItem('isRTL'));
      if (isRTL) {
        var linkDefault = document.getElementById('style-default');
        var userLinkDefault = document.getElementById('user-style-default');
        linkDefault.setAttribute('disabled', true);
        userLinkDefault.setAttribute('disabled', true);
        document.querySelector('html').setAttribute('dir', 'rtl');
      } else {
        var linkRTL = document.getElementById('style-rtl');
        var userLinkRTL = document.getElementById('user-style-rtl');
        linkRTL.setAttribute('disabled', true);
        userLinkRTL.setAttribute('disabled', true);
      }
    </script>
  </head>


  <body>

templates/_left_nav.html
<nav class="navbar navbar-light navbar-vertical navbar-expand-xl">
    <div class="d-flex align-items-center">
        <a class="navbar-brand" href="/">
            <div class="d-flex align-items-center py-3"><img class="me-2"
                                                             src="/static/assets/img/unpaywall_logo.png" height="30"/>
            </div>
        </a>
    </div>
    <!-- Menu items -->
    <div class="collapse navbar-collapse" id="navbarVerticalCollapse">
        <div class="navbar-vertical-content scrollbar">
            <ul class="navbar-nav flex-column mb-3" id="navbarVerticalNav">
                <li class="nav-item">
                    <a class="nav-link" href="/">
                        <div class="d-flex align-items-center"><span class="nav-link-icon"><span
                                class="fas fa-home"></span></span><span class="nav-link-text">Home</span></div>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/guide">
                        <div class="d-flex align-items-center"><span class="nav-link-icon"><span
                                class="fas fa-book"></span></span><span class="nav-link-text">Guide</span></div>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/refresh-doi">
                        <div class="d-flex align-items-center"><span class="nav-link-icon"><span
                                class="fas fa-sync"></span></span><span class="nav-link-text">Refresh multiple DOIs</span></div>
                    </a>
            </ul>
        </div>
    </div>
</nav>

templates/_top_nav.html
<nav class="navbar navbar-light navbar-glass navbar-top navbar-expand">
    <button class="btn navbar-toggler-humburger-icon navbar-toggler me-1 me-sm-3" type="button"
            data-bs-toggle="collapse" data-bs-target="#navbarVerticalCollapse" aria-controls="navbarVerticalCollapse"
            aria-expanded="false" aria-label="Toggle Navigation"><span class="navbar-toggle-icon"><span
            class="toggle-line"></span></span></button>
    <ul class="navbar-nav navbar-nav-icons ms-auto flex-row align-items-center">
        <li class="nav-item dropdown"><a class="nav-link pe-0 ps-2" id="navbarDropdownUser" role="button"
                                         data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <div class="avatar avatar-xl">
                <img class="rounded-circle" src="/static/assets/img/user.png" alt=""/>

            </div>
        </a>
            <div class="dropdown-menu dropdown-caret dropdown-caret dropdown-menu-end py-0"
                 aria-labelledby="navbarDropdownUser">
                <div class="bg-white dark__bg-1000 rounded-2 py-2">
                    <a class="dropdown-item" href="/logout">Logout</a>
                </div>
            </div>
        </li>
    </ul>
</nav>

templates/base.html
{% include "_header.html" %}
<main class="main" id="top">
    <div class="container" data-layout="container">
        {% include "_left_nav.html" %}
        <div class="content">
            {% include "_top_nav.html" %}
            {% block content %}{% endblock %}
            {% include "_footer.html" %}
        </div>
    </div>
</main>
<!-- ===============================================-->
<!--    JavaScripts-->
<!-- ===============================================-->
<script src="/static/vendors/popper/popper.min.js"></script>
<script src="/static/vendors/bootstrap/bootstrap.min.js"></script>
<script src="/static/vendors/anchorjs/anchor.min.js"></script>
<script src="/static/vendors/is/is.min.js"></script>
<script src="/static/vendors/fontawesome/all.min.js"></script>
<script src="/static/vendors/lodash/lodash.min.js"></script>
<script src="https://polyfill.io/v3/polyfill.min.js?features=window.scroll"></script>
<script src="/static/vendors/list.js/list.min.js"></script>
<script src="/static/assets/js/theme.js"></script>

</body>

</html>

templates/guide.html
{% extends 'base.html' %}

{% block content %}
    <!-- Header -->
    <div class="card mb-3">
        <div class="bg-holder d-none d-lg-block bg-card"
             style="background-image:url(/static/assets/img/icons/spot-illustrations/corner-4.png);">
        </div>
        <!--/.bg-holder-->

        <div class="card-body position-relative">
            <div class="row">
                <div class="col-lg-8">
                    <h3 class="mb-0">Guide - common problems</h3>
                </div>
            </div>
        </div>
    </div>

    <div class="card">
        <div class="card-body">
            <h5 class="card-title">How to check a DOI</h5>
            <p>When someone says something is wrong with an article, follow these steps to check if there is a problem.</p>
            <ol>
                <li>Get the DOI from the ticket, or if the person links to an article, go to the article and find the DOI.</li>
                <li>Enter the DOI into the dashboard so you can see the details.</li>
                <li>Go to the "official" version of the article, which is found by clicking the blue arror next to the DOI. This
                 is the same as going to https://doi.org/exampledoi</li>
                <li>Look at the article title, authors, and see if you have to pay to access the article.</li>
                <li>Go back to the dashboard and look at the link that we have under Best OA Location -> URL. Visit this link.
                Does the article it goes to match the official version? If the article is free on the official version then
                we should point to that.</li>
                <li>If the official version of the article is not free, are we pointing to another version? Does it match the
                title and authors (generally)? If so then everything is correct, if not, try refreshing.</li>
                <li>After refreshing, has the link changed? If you have to pay to access the article, and the link we are
                pointing to is an incorrect article, then click Close DOI.</li>
                <li>If the official version is free and we are not pointing to it, and refreshing does not change anything, then there
                is nothing else you can do. Likely we are having problems scraping the official site. Leave the ticket open.</li>
            </ol>
        </div>
{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block content %}
    <!-- Header -->
    <div class="card mb-3">
        <div class="bg-holder d-none d-lg-block bg-card"
             style="background-image:url(/static/assets/img/icons/spot-illustrations/corner-4.png);">
        </div>
        <!--/.bg-holder-->

        <div class="card-body position-relative">
            <div class="row">
                <div class="col-lg-8">
                    <h3 class="mb-0">Unpaywall Dashboard</h3>
                </div>
            </div>
        </div>
    </div>

    <!-- Submit DOI Form -->
    {% if not result and not not_in_unpaywall %}
        {% include "index_doi_form.html" %}
    {% endif %}

    <!-- Results -->
    {% if result %}
        <div class="card mb-3">
            <!-- Result header -->
            <div class="card-header">
                <div class="row flex-between-end">
                    <div class="col-auto align-self-center">
                        <h5 class="mb-0">DOI {{ doi }} <a href="{{ result.doi_url }}" target="_blank">
                            <icon class="fas fa-external-link-square-alt"></icon></a> <a href="https://api.unpaywall.org/v2/{{ result.doi_url }}?email=support@unpaywall.org" target="_blank">
                            <icon class="fas fa-code"></icon>
                        </a></h5>
                    </div>
                    <div class="col-auto ms-auto">
                        <div class="flex-grow-1">
                            <button class="btn btn-primary btn-sm" onclick="refreshDoi()" id="refreshDoiButton">Refresh
                            </button>
                            {% if manually_closed %}
                                <a href="/open-doi?doi={{ doi }}" class="btn btn-success btn-sm">Open DOI</a>
                            {% else %}
                                <a href="/add-manual?doi={{ doi }}" class="btn btn-danger btn-sm">Close DOI</a>
                            {% endif %}
                        </div>
                    </div>
                    <div class="card-body">
                        <h5>{{ result.title }}</h5>
                        <p>Published by {{ result.publisher }} in {{ result.journal_name }}
                            on {{ result.published_date }}</p>
                        <p>{% if result.is_oa %}
                            <span class="badge badge-soft-success">Open Access</span>
                            {% if result.oa_status == "gold" %}
                                <span class="badge" style="color: black; background-color: #FFD700">{{ result.oa_status }}</span>
                            {% elif result.oa_status == "green" %}
                                <span class="badge bg-success">{{ result.oa_status }}</span>
                            {% elif result.oa_status == "bronze" %}
                                <span class="badge" style="background-color: #CD7F32">{{ result.oa_status }}</span>
                            {% else %}
                                <span class="badge bg-info">{{ result.oa_status }}</span>
                            {% endif %}
                        {% else %}
                            <span class="badge badge-soft-danger">Closed</span>
                        {% endif %}</p>
                        <div class="row">
                            <div class="col-12">
                                <div class="overflow-hidden mt-4">
                                    {% include "index_tab_menu.html" %}
                                    <div class="tab-content" id="myTabContent">
                                        {% include "index_tab_best_oa.html" %}
                                        {% include "index_tab_journal.html" %}
                                        {% include "index_tab_other_oa.html" %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-footer border-top">
                    <a class="btn btn-falcon-default btn-sm" href="/">New Search</a>
                </div>
            </div>
        </div>
        {% include "index_script.html" %}
    {% elif not_in_unpaywall %}
        <div class="card mb-3">
            <div class="card-body">
                <h5>DOI {{ doi }} is not in Unpaywall</h5>
                <br>
                <p><a href="https://api.crossref.org/works/{{doi}}" target="_blank">Is it in crossref</a>?</p>
                <p>If not check the help article <a href="https://support.unpaywall.org/support/solutions/articles/44001900286-which-dois-does-unpaywall-cover-">here</a>.</p>
            </div>
            <div class="card-footer border-top">
                <a class="btn btn-falcon-default btn-sm" href="/">New Search</a>
            </div>
        </div>
    {% endif %}
{% endblock %}

templates/index_doi_form.html
<div class="card mb-3">
    <div class="card-header">
        <h5 class="mb-0" id="quick-start">Look up a DOI</h5>
    </div>
{% if message %}
    <div class="alert" role="alert">
        {{ message }}
    </div>
    {% endif %}
    <div class="card-body bg-light">
        <form action="/" method="GET">
            <div class="mb-3">
                {{ form.doi.label(class="form-label") }}
                {{ form.doi(class="form-control") }}
                {% if form.doi.errors %}
                    <ul class="errors">
                        {% for error in form.doi.errors %}
                            <li>{{ error }}</li>{% endfor %}
                    </ul>
                {% endif %}
            </div>
            {{ form.submit(class="btn btn-primary") }}
        </form>
    </div>
</div>

templates/index_script.html
<script>
    function refreshDoi() {
        fetch("/refresh-doi/{{ doi }}")
            .then((response) => response.json())
            .then((data) => getStatus(data.job_id));
    }

    function getStatus(jobId) {
        fetch("/refresh-status/" + jobId)
            .then((response) => response.json())
            .then((data) => {
                if (data.status === "queued" || data.status === "started") {
                    // change button to spinner and text to "Refreshing..."
                    document.getElementById("refreshDoiButton").innerHTML = '<span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span> Refreshing...';
                    console.log(data.status);
                    // loop every 2 seconds
                    setTimeout(() => getStatus(jobId), 2000);
                } else if (data.status === "finished") {
                    if (data.result.switched_to_closed) {
                        document.getElementById("refreshDoiButton").innerHTML = 'Switched to Closed';
                        document.getElementById("refreshDoiButton").classList.remove("btn-primary");
                        document.getElementById("refreshDoiButton").classList.add("btn-success");
                    } else if (data.result.switched_to_open) {
                        document.getElementById("refreshDoiButton").innerHTML = 'Switched to Open';
                        document.getElementById("refreshDoiButton").classList.remove("btn-primary");
                        document.getElementById("refreshDoiButton").classList.add("btn-success");
                    } else if (data.result.is_changed) {
                        document.getElementById("refreshDoiButton").innerHTML = 'Changed';
                        document.getElementById("refreshDoiButton").classList.remove("btn-primary");
                        document.getElementById("refreshDoiButton").classList.add("btn-success");
                    } else {
                        document.getElementById("refreshDoiButton").innerHTML = 'No Change';
                        document.getElementById("refreshDoiButton").classList.remove("btn-primary");
                        document.getElementById("refreshDoiButton").classList.add("btn-success");
                    }
                } else {
                    // change button class to danger and text to "Error"
                    document.getElementById("refreshDoiButton").innerHTML = 'Error';
                    document.getElementById("refreshDoiButton").classList.remove("btn-primary");
                    document.getElementById("refreshDoiButton").classList.add("btn-danger");
                }
            });
    }
</script>

templates/index_tab_best_oa.html
<div class="tab-pane fade active show" id="tab-best-oa"
     role="tabpanel" aria-labelledby="best-oa-tab">
    <div class="mt-3">
        <table class="table table-borderless">
            <tbody>
            {% if result.best_oa_location and result.best_oa_location.url %}
                <tr>
                    <td>URL</td>
                    <td>
                        <a href="{{ result.best_oa_location.url }}">{{ result.best_oa_location.url }}</a>
                    </td>
                </tr>
            {% endif %}
            {% if result.best_oa_location and result.best_oa_location.url_for_pdf %}
                <tr>
                    <td>PDF URL</td>
                    <td>
                        <a href="{{ result.best_oa_location.url_for_pdf }}">{{ result.best_oa_location.url_for_pdf }}</a>
                    </td>
                </tr>
            {% endif %}
            {% if result.best_oa_location and result.best_oa_location.url_for_landing_page %}
                <tr>
                    <td>Landing Page URL</td>
                    <td>
                        <a href="{{ result.best_oa_location.url_for_landing_page }}">{{ result.best_oa_location.url_for_landing_page }}</a>
                    </td>
                </tr>
            {% endif %}
            {% if http_url %}
                <tr>
                    <td>Convert http URL to https?</td>
                    <td>
                        Does this http link <a href="{{ http_url }}" target="_blank">{{ http_url }}</a> work the same as this
                        <a href="{{ http_url | replace('http://', 'https://') }}" target="_blank">https</a> version?
                        If so, <a href="{{ url_for('dashboard.convert_domain_to_https', doi=doi, url=http_url) }}">click here</a> to convert it to https.
                    </td>
                </tr>
            {% endif %}
            {% if result.best_oa_location and result.best_oa_location.evidence %}
                <tr>
                    <td>Evidence</td>
                    <td>{{ result.best_oa_location.evidence }}</td>
                </tr>
            {% endif %}
            {% if result.best_oa_location and result.best_oa_location.license %}
                <tr>
                    <td>Evidence</td>
                    <td>{{ result.best_oa_location.license }}</td>
                </tr>
            {% endif %}
            {% if result.best_oa_location and result.best_oa_location.version %}
                <tr>
                    <td>Version</td>
                    <td>{{ result.best_oa_location.version }}</td>
                </tr>
            {% endif %}
            {% if result.best_oa_location and result.best_oa_location.host_type %}
                <tr>
                    <td>Host Type</td>
                    <td>{{ result.best_oa_location.host_type }}</td>
                </tr>
            {% endif %}
            {% if result.best_oa_location and result.best_oa_location.pmh_id %}
                <tr>
                    <td>PMH ID</td>
                    <td>{{ result.best_oa_location.pmh_id }}</td>
                </tr>
            {% endif %}
            {% if result.best_oa_location and result.best_oa_location.endpoint_id %}
                <tr>
                    <td>Endpoint ID</td>
                    <td>{{ result.best_oa_location.endpoint_id }}</td>
                </tr>
            {% endif %}
            {% if result.best_oa_location and result.best_oa_location.repository_institution %}
                <tr>
                    <td>Repository Institution</td>
                    <td>{{ result.best_oa_location.repository_institution }}</td>
                </tr>
            {% endif %}
            {% if result.best_oa_location and result.best_oa_location.oa_date %}
                <tr>
                    <td>OA Date</td>
                    <td>{{ result.best_oa_location.oa_date }}</td>
                </tr>
            {% endif %}
            {% if result.updated %}
                <tr>
                    <td>Updated</td>
                    <td>{{ result.updated }}</td>
                </tr>
            {% endif %}
            </tbody>
        </table>
    </div>
</div>

templates/index_tab_journal.html
<div class="tab-pane fade" id="tab-journal" role="tabpanel"
     aria-labelledby="journal-tab">
    <div class="mt-3">
        <table class='table table-borderless'>
            <tbody>
            <tr>
                <td>Name</td>
                <td>{{ result.journal_name }}</td>
            </tr>
            <tr>
                <td>Publisher</td>
                <td>{{ result.publisher }}</td>
            </tr>
            <tr>
                <td>Journal is Open Access</td>
                <td>{{ result.journal_is_oa }}</td>
            </tr>
            <tr>
                <td>Journal is In DOAJ</td>
                <td>{{ result.journal_is_in_doaj }}</td>
            </tr>
            <tr>
                <td>ISSN-L</td>
                <td>{{ result.journal_issn_l }}</td>
            </tr>
            <tr>
                <td>ISSNs</td>
                <td>{{ result.journal_issns }}</td>
            </tr>
            </tbody>
        </table>
        <form method="get" action="/journal-oa-year-override">
            <p>Mark this journal as open access beginning with this year:</p>
            <input type="hidden" name="issn_l" value="{{ result.journal_issn_l }}">
            <input name="year" type="number" placeholder="Year">
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>